language: c
compiler:
  - gcc
  - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq junit
script: make -k && sudo python setup.py install && make test && python s3ptest.py && make javatests